[defense]
titan-core-01 ansible_host=192.168.1.240 ansible_user=titanadmin

[attack]
kali-node-01 ansible_host=192.168.1.241 ansible_user=titan

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
