[defense]
titan-core-01 ansible_host=192.168.1.240 ansible_user=titanadmin ansible_ssh_private_key_file=~/.ssh/id_ed25519

[attack_platform]
kali-node-01 ansible_host=192.168.1.241 ansible_user=titan # Use a generic attack user here
