---
- name: Create Proxy Directory
  file:
    path: "{{ proxy_config_path }}"
    state: directory
    mode: '0755'

- name: Deploy Traefik Config
  template:
    src: traefik.yml.j2
    dest: "{{ proxy_config_path }}/traefik.yml"

- name: Deploy Proxy Compose File
  template:
    src: docker-compose.yml.j2
    dest: "{{ proxy_config_path }}/docker-compose.yml"

- name: Launch Traefik
  community.docker.docker_compose_v2:
    project_src: "{{ proxy_config_path }}"
    state: present
